### ISSUE TITLE
Incorrect well-definedness checks

### ISSUE THREAD

**Issue by viper-admin** [viperproject/gobra#11]
> Created by **@Felalolf** on 2019-09-25 14:29

The CodeWriter aggregator can collect well-definedness conditions generated during translation.

However, currently such well-definedness conditions are not correctly translated.

Especially, the differences between an assuming position, an asserting position, and an invariant position are not properly implemented.

If I am not mistaken, then the encoding should be as follows:

‌

```
Asserting<e> -> W(e) && <e>, where W(.) is the well-definedness condition
Assuming<e>  -> assert W(e); <e>

Or if the translated code has to be a single assertion:
AssumingPure<e> -> assertThen(W(e), <e>)
  where
    function assertThen(ass: Bool, res: T): T
      requires ass
      ensures  res
```

According to Marco, the single assertion encoding using \`assertThen\` has a bad impact on performance.

‌

**Comment by Felalolf** [comment]
This should have been fixed in #89. The corresponding function generation was added.
