### ISSUE TITLE
Consolidating the Parser

### ISSUE THREAD

**Issue by viper-admin** [viperproject/gobra#13]
> Created by **@Felalolf** on 2019-09-25 15:48

I constructed the Gobra parser by essentially taking the Voila parser and adapting it according to the Go language syntax \([golang.org/ref/spec](http://golang.org/ref/spec)\).

The advantage of this approach was that I was able to construct the parser quickly.

However, as one should expect, the maintainability and extendability of the parser are questionable.

At some point, someone with sufficient foundational knowledge about parser should go over the parser and consolidate it.

**Comment by jcp19** [comment]
Taken care of in #388
