### ISSUE TITLE
No support for blank identifier in assignments

### ISSUE THREAD

**Issue by jcp19** [viperproject/gobra#135]
It is a common idiom in Go to assign an expression to a blank identifier when its result is ignored:
```go
  x, _ := 1, i
```

However, doing that in Gobra leads to a parser error
```
/Users/joao/Desktop/Example.gobra:74:6: string matching regex '(?:_[a-zA-Z0-9_]+|[a-zA-Z][a-zA-Z0-9_]*)' expected but '_' found
  x, _ := 1, i;
     ^
```

**Comment by Aurel300** [comment]
`(?:_[a-zA-Z0-9_]*|[a-zA-Z][a-zA-Z0-9_]*)` (replacing the `+` with `*`) should work.

**Comment by jcp19** [comment]
Thanks for your input :) The problem is not so much with the parser. Instead, it is related to the encoding of the blank identifier. `_` is not a valid identifier, e.g. you cannot use a variable named `_` as an operand for an arithmetic expression - that is why it was out-ruled by the first branch. It seems to me that the way to fix it is to extend the parser to support a new symbol for the `_` and  to extend the desugarer to encode the LHS part of the assignment (corresponding to the `_`) as a fresh variable. This has the advantage that our parser will still refuse programs like the following, while accepting correct uses of the blank identifier
```go
x, _ := 1, 2
fmt.Print(x + _)
```
