### ISSUE TITLE
If statements with empty body

### ISSUE THREAD

**Issue by wytseoortwijn** [viperproject/gobra#143]
Gobra seems to give a parsing error on the following:
```go
func foo(x int, y int) {
  if x < y {
  }
  z := x + y
}
```
The problem seems to be the empty body of the if statement. Interestingly, Gobra is fine with:
```go
func foo(x int, y int) {
  if (x < y) {
  }
  z := x + y
}
```
as well as with e.g.:
```go
func foo(x int, y int) {
  if x < y {
    w := 0
  }
  z := x + y
}
```

**Comment by ArquintL** [comment]
I think this is a duplicate of #93

**Comment by wytseoortwijn** [comment]
Aah indeed, thanks! In that case I'll close this issue.
