### ISSUE TITLE
Problems with abstract ghost functions

### ISSUE THREAD

**Issue by wytseoortwijn** [viperproject/gobra#145]
Gobra currently gives a parsing error saying "'func' expected but 'g' found" on:
```go
requires forall i int :: 0 <= i && i < len(s) ==> acc(&s[i])
ghost pure func foo (s []int) seq[int]
```

Removing the precondition would resolve the error, as would changing the program into:
```go
requires forall i int :: 0 <= i && i < len(s) ==> acc(&s[i])
pure func foo (s []int) (ghost seq[int])
```

However, after slightly extending the above snippet I got into (typing) errors. Gobra explains about `foo(s)[i]` in the snippet below, saying "got unknown identifier `i`", and also giving a property error.
```go
requires forall i int :: 0 <= i && i < len(s) ==> acc(&s[i])
ensures len(foo(s)) == len(s)
ensures forall i int :: 0 <= i && i < len(s) ==> s[i] == foo(s)[i]
pure func foo (s []int) (ghost seq[int])
```

I tried to fix this by adding parentheses and writing `(foo(s))[i]` instead, but then I got "Unexpected output of Z3. Expected 'success' but found: (error "line 1227 column 17: unknown constant i_pkg_V4@22@00")"

**Comment by ArquintL** [comment]
I can confirm the annoyance of having to write `(foo(s))[i]`. However, I've encountered a parser error if a function is called without arguments, i.e. `n.left.orderedValues()[i]`.

Commenting on the first part, the `ghost` keyword has to be placed before preconditions:
```
ghost
requires forall i int :: 0 <= i && i < len(s) ==> acc(&s[i])
pure func foo (s []int) seq[int]
```

**Comment by jcp19** [comment]
Gobra no longer reports the same parsing error after #388. Instead, it reports
```
[info] Gobra has found 1 error(s) in package /Users/joao/Desktop/parsing - test
[info] 	</Users/joao/Desktop/parsing/145.gobra:4:0> Unexpected reserved word ghost.
[info] ghost pure func foo (s []int) seq[int]
[info] ^^^^^
```

This looks OK to me. However, we still have an exception in the last snippet
```
[info] An unknown Exception was thrown.
[info] viper.silicon.reporting.Z3InteractionFailed: Unexpected output of Z3. Expected 'success' but found: (error "line 1806 column 16: unknown constant i_aab46edc581e80052046aea505ffa85b79df36aa_V2@18@00")
```

**Comment by Felalolf** [comment]
The Z3 exception is a different issue. I created an issue for that #454.
