### ISSUE TITLE
Ownership of struct fields not on the heap

### ISSUE THREAD

**Issue by viper-admin** [viperproject/gobra#15]
> Created by bitbucket user **Wytse Oortwijn** on 2019-10-01 12:41
> Last updated on 2019-10-01 12:57

Gobra currently tolerates the `requires` clause in:  

```go
package main;

type Cell struct {
	val int;
};

requires acc(c.val);
func test (c Cell) { };
```

In the Viper encoding `acc(c.val)` seems to be discarded. Should Gobra not complain here?

**Comment by Felalolf** [comment]
Due to the new encoding, Gobra will crash if acc is used with something that has no permissions. In a next PR, I will add that these programs are rejected.
