### ISSUE TITLE
Support for the error type

### ISSUE THREAD

**Issue by jcp19** [viperproject/gobra#158]
The type `error` is ubiquitous in *Go* code and, in particular, it is used extensively throughout the *SCION* codebase. As such, it would be very useful to implement it in *Gobra*. 

It is defined as
```go
type error interface {
    Error() string
}
```

Gobra does not support non-empty interfaces and the `string` type at the moment. Nevertheless, it may still be worth to implement a pared down version of `error` (e.g.  as an empty interface) so that it can parse (some) code that relies on it (e.g. code that does not call `Error()` on a receiver with static type `error`). SCION is full of usages of `error` that satisfy this criterion - commonly, `error` is just used as a return type.

**Comment by jcp19** [comment]
There are two possible solutions for this issue:
1. implement error suing the mechanism for BuiltIn identifiers developed by @ArquintL 
2. implement a package that is implicitly imported for every gobra file and that requires no qualification to access its members.

**Comment by ArquintL** [comment]
As discussed, approach (2) probably requires less work right now but even less in the future to add additional types or built-in functions and members
