### ISSUE TITLE
NodeNotInTreeException in imported n-ary mpredicates (n > 0)

### ISSUE THREAD

**Issue by jcp19** [viperproject/gobra#169]
*Gobra* crashes with the following files
- `bla/imported.gobra`
```go
package bla

type T struct {}

pred (t *T)mPred(x int)
```
- `import_pred.gobra`
```go
package pkg

import "bla"

requires t.mPred(y)
pure func f(t* bla.T, y int) int
```
with the following stack trace
```
[error] Exception in thread "main" org.bitbucket.inkytonik.kiama.relation.NodeNotInTreeException: node not in tree: x int
[error] 	at org.bitbucket.inkytonik.kiama.relation.TreeRelation.apply(TreeRelation.scala:53)
[error] 	at viper.gobra.frontend.info.implementation.typing.BaseTyping.children(BaseTyping.scala:50)
[error] 	at viper.gobra.frontend.info.implementation.typing.BaseTyping.children$(BaseTyping.scala:49)
[error] 	at viper.gobra.frontend.info.implementation.TypeInfoImpl.children(TypeInfoImpl.scala:22)
[error] 	at viper.gobra.frontend.info.implementation.typing.BaseTyping.childrenWellDefined(BaseTyping.scala:52)
[error] 	at viper.gobra.frontend.info.implementation.typing.BaseTyping.childrenWellDefined$(BaseTyping.scala:52)
[error] 	at viper.gobra.frontend.info.implementation.TypeInfoImpl.childrenWellDefined(TypeInfoImpl.scala:22)
[error] 	at viper.gobra.frontend.info.implementation.typing.BaseTyping$$anon$1.safe(BaseTyping.scala:68)
[error] 	at viper.gobra.frontend.info.implementation.typing.BaseTyping$$anon$1.safe(BaseTyping.scala:66)
```
If `mPred` is declared with no parameters (besides the receiver), then Gobra runs as expected

**Comment by jcp19** [comment]
Besides, no exception is thrown if mpred is changed to
```go 
pred mPred(t *T, x int)
```
(with the necessary changes in `import_pred.gobra`

**Comment by ArquintL** [comment]
My guess: The type checker tries to check whether the type of `y` in `t.mPred(y)` conforms to the signature and to do so gets the parameter `x int`. Apparently, it uses the wrong context, i.e. the context of package `pkg` instead of `bla`, to perform some operation on the parameter (such as getting the type).

Reacting to your second finding: The correct context seems to be used for fpredicates but not for mpredicates

**Comment by jcp19** [comment]
Yes @ArquintL that seems to be exactly the case! In the method `exprAndTypeType` of file `ExprTyping.scala`, the case for a `ReceivedPredicate` relies on the method `memberType` which does not set-up the right context whereas the case for regular predicates is implemented as
```scala
        case Some(p: ap.Predicate) => FunctionT(p.symb.args map p.symb.context.typ, AssertionT)
```

**Comment by jcp19** [comment]
I will provide a fix for this
