### ISSUE TITLE
Support for break is broken (continue too)

### ISSUE THREAD

**Issue by MartinClochard** [viperproject/gobra#171]
Gobra does not handle break/continue. I ran in the issue with the following example:
```
package pkg

ghost pure func prime(p int) bool {
  return p >= 2 &&
    forall a, b int :: a >= 0 && b >= 0 && a * b == p ==> a == 1 || b == 1
}

ghost
requires n >= 2 && !prime(n)
ensures prime(p) && p * k == n
ensures p * p <= n
func prime_div(n int) (p int,k int) {
  p = 2
  invariant forall a, b int ::
    a >= 0 && b >= 0 && a < p && a * b == n ==> a == 1
  for ;p * p <= n; p++ {
    if(n % p == 0) { break }
  }
  k = n / p
}
```
Gobra fails with a large exception stack, and the exception: "Exception in thread "main" viper.gobra.util.Violation$LogicException: Logic error: break was not handled". The same issue arise when replacing break with continue (though it make no sense for that particular piece of code).

**Comment by Felalolf** [comment]
Technically, the support is not broken, I simply did not attend to support them right now.

**Comment by jcp19** [comment]
Related to this, `continue` is also currently not supported
