### ISSUE TITLE
Wrong Postcondition Encoding for Pure Method

### ISSUE THREAD

**Issue by ArquintL** [viperproject/gobra#180]
The following program results in a Viper file in which the postcondition of `test1` and `test3` do not refer to `result` but an undeclared variable:
```
package pkg

type Tree struct {}

ghost
ensures forall i int :: (0 <= i && i + 1 < len(res) ==> res[i] < res[i + 1])
pure func (t *Tree) test1() (res seq[int]) {
    return seq[int] { }
}

ghost
ensures forall i int :: (0 <= i && i + 1 < len(res) ==> res[i] < res[i + 1])
pure func test2() (res seq[int]) {
    return seq[int] { }
}

ensures forall i int :: (0 <= i && i + 1 < len(res) ==> res[i] < res[i + 1])
pure func (t *Tree) test3() (ghost res seq[int]) {
    return seq[int] { }
}

ensures forall i int :: (0 <= i && i + 1 < len(res) ==> res[i] < res[i + 1])
pure func test4() (ghost res seq[int]) {
    return seq[int] { }
}
```

**Comment by Felalolf** [comment]
A simple trick is to just replace a variable with `vpr.Result` in the translated Viper expression. For that you can use the `transform` method, defined on `vpr.Exp`. E.g. `e.transform{ case x: vpr.LocalVar if x.name == resDummy.id => vpr.Result(vResType)() }` where `resDummy` is the variable that has to be replaced with `vpr.Result`. 

PS: Using different versions of tranform that match directly on the variable are quite error prone from my experience. That is why I usually map on `vpr.LocalVar` and check for the name.

**Comment by ArquintL** [comment]
Found it, the reason why it didn't work as intended was that a fruitless comparison was performed. Stay tuned for the PR ;)
