### ISSUE TITLE
Permissiveness towards variable declarations

### ISSUE THREAD

**Issue by ArquintL** [viperproject/gobra#200]
Gobra currently allows short variable declarations where Go disallows them. The following snippet from `heapsort.gobra` shows such an instance.
However, verification succeeds if start is redeclared (using the short var decl) but the invariant does not hold of it's changed to a simple assignment (as Go enforces it). Looking at the Viper sources, a second variable is declared in Viper to which `start -1` is assigned to. This additional variable is not used anywhere else.
```
requires forall n int :: 0 <= n && n < len(s) ==> acc(&s[n])
ensures forall n int :: 0 <= n && n < len(s) ==> acc(&s[n])
ensures forall n int :: 0 <= parent(n) && n < len(s) ==> s[n] <= s[parent(n)]
func heapify (s []int) {
  start := parent(len(s) - 1)
  
  invariant -1 <= start && start <= parent(len(s) - 1)
  invariant forall n int :: 0 <= n && n < len(s) ==> acc(&s[n])
  invariant forall n int :: start + 1 <= parent(n) && n < len(s) ==> s[n] <= s[parent(n)]
  for (0 <= start) {
    siftDown(s, start, len(s) - 1, false)
    start := start - 1
  }
}
```

**Comment by Felalolf** [comment]
I do not understand your statement. In Go, I can write the following:
```
	x := 0
	for (x < 100) {
	  fmt.Println("A: ", x)
	  x := x + 1
	  fmt.Println("B: ", x)
	}
```
And it behaves exactly as encoded in Gobra. the `x := x + 1`declares a new variable and the output is an infinite loop of "A: 0" and "B: 1". We do not check that all variables are actually used, but my general opinion on this is that it is fine to require that the program was type checked by a Go compiler. In a sense, we simply support more programs than just Go programs. Important is that we verify soundly on all Go programs.

**Comment by ArquintL** [comment]
Oh okay I did not know this. I simply assumed that you cannot declare a second variable with the same name.
I agree with you that this is fine from the perspective of Gobra
