### ISSUE TITLE
In-file config is not relative to file 

### ISSUE THREAD

**Issue by ArquintL** [viperproject/gobra#243]
Paths in in-file configs should be relative to the file not to where Gobra is executed

**Comment by ArquintL** [comment]
@jcp19 the work is on branch `issue-243`. As discussed, the test cases using in file include dirs need to be adapted. In addition, adding a test case that joins (and resolves) in-file configs from two different files would be nice to show that both include dirs are then actually used

**Comment by jcp19** [comment]
Thanks @ArquintL!

**Comment by jcp19** [comment]
As @ArquintL suggested, running gobra with the `-I` flag pointing to the include path should be enough.

**Comment by jcp19** [comment]
This seems to have been fixed in PR #263
