### ISSUE TITLE
Add option to specify the path used in GobraTests

### ISSUE THREAD

**Issue by jcp19** [viperproject/gobra#245]
Currently, the `testDirectories` in the GobraTests class has the value `Vector("regressions")` hardwired.

For the VerifiedSCION project, I want to test every .gobra file in the repository whenever there is a new commit. For that, I was hoping to reuse the existing testing framework on this repository. This requires the ability to specify the folder with the .gobra files in `GobraTests`

**Comment by jcp19** [comment]
This can be done without the gobra test framework

**Comment by ArquintL** [comment]
@jcp19 since the artifact, there is now also the option to pass `-DGOBRATESTS_REGRESSIONS_DIR=<dir to gobra files>` to `GobraTests`. Maybe this is an alternative option for you
