### ISSUE TITLE
Go Method Call to Foreign Method

### ISSUE THREAD

**Issue by ArquintL** [viperproject/gobra#272]
Performing a go method call to an imported method results in a silicon exception.

Steps to reproduce:
Add the following snippet to `import/method_import/main.gobra`:
```
func foo2() {
    r@ := b.Rectangle{Width: 2, Height: 5}
    go r.Area()
    // go (*(b.Rectangle)).Area(&r)
}
```

or the following to `import/method_import/main2.gobra`:
```
func foo2() {
    r := b.CreateRectangle()
    go r.Area()
    go (*(b.Rectangle)).Area(r)
}
```

**Comment by Felalolf** [comment]
The bug is that the desugaring step does not transform `r.Area()` to `&r.Area()`
