### ISSUE TITLE
Feature Request: Gobra backwards-compatibility with Go compiler

### ISSUE THREAD

**Issue by terorie** [viperproject/gobra#284]
As far as I can tell, adding Gobra code to an existing Go project requires copying all files from `.go` to `.gobra` files.
The current file format of `.gobra` is not compatible with the Go compiler and has to be transpiled into `.go` before building. I fear this might make adding Gobra verification to a program too invasive to existing build pipelines and hamper adoption of this remarkable tooling.

Have you considered placing the Gobra DSL extensions into Go comments instead to preserve backwards compatibility with the Go compiler? 

Several other extensions take this approach, for example:
* `embed`: https://golang.org/pkg/embed/ (via `//go:embed`)
* `cgo`: https://golang.org/cmd/cgo/
* golangci-lint: https://golangci-lint.run/usage/false-positives/

The Gobra syntax looks like this currently (taken from the tutorial)

```go
package tutorial

ensures res == (n % 2 == 0)
pure func isEven(n int) (res bool) {
  return n % 2 == 0
}

ensures isEven(n) ==> res == n / 2
ensures !isEven(n) ==> res == n / 2 + 1
func halfRoundedUp(n int) (res int) {
  if isEven(n) {
    res = n / 2
  } else {
    res = n / 2 + 1
  }
  return res
}
```

A new syntax inspired by the other Go language extensions could look like this.

```go
package tutorial

//gobra:pure
//gobra:ensures res == (n % 2 == 0)
func isEven(n int) (res bool) {
  return n % 2 == 0
}

//gobra:ensures isEven(n) ==> res == n / 2
//gobra:ensures !isEven(n) ==> res == n / 2 + 1
func halfRoundedUp(n int) (res int) {
  if isEven(n) {
    res = n / 2
  } else {
    res = n / 2 + 1
  }
  return res
}
```

**Comment by Felalolf** [comment]
Thank you for the suggestion. We intend that Gobra can be run on `.gobra` and `.go` files. 
For `.go` files, as you suggested, the Gobra annotations are written as comments. 
As in Verifast and VerCors, we use `//@` for single-line comments and `/*@ ... @*/` for multi-line comments.
Your example then looks as follows:
```
package tutorial

//@ pure
//@ ensures res == (n % 2 == 0)
func isEven(n int) (res bool) {
  return n % 2 == 0
}

//@ ensures isEven(n) ==> res == n / 2
//@ ensures !isEven(n) ==> res == n / 2 + 1
func halfRoundedUp(n int) (res int) {
  if isEven(n) {
    res = n / 2
  } else {
    res = n / 2 + 1
  }
  return res
}
```
If requested, we could make the delimiter (`@` by default) configurable.

We have developed a Visual Studio Code plugin that supports the verification of `.go` files directly. Furthermore, the plugin offers commands to transform between a `.go` and `.gobra` file. The plugin is not published right now, but we expect that this will happen in the near future (we are updating our IDE infrastructure). I expect that we will add the same capabilities to a command-line tool.

Once these features are published, we will extend the tutorial. The syntax is straightforward, except ghost parameters and shared annotations, which are treated a bit differently.

**Comment by terorie** [comment]
@Felalolf Thank you very much, that solves my problem. Feel free to close then. 

> If requested, we could make the delimiter (@ by default) configurable.

imho, this should be a last resort if there are conflicts. I like `@`, it's short, bold and easy-to-type on most keyboard layouts. I consider Gobra go-style an extension to the Go language itself where `//@` serves as an (unreserved) keyword. Keywords usually aren't configurable to keep the language complexity down.
The Go language developers are more qualified to comment though. Have you checked with them?

**Comment by Felalolf** [comment]
The aforementioned projects have been published (a while ago).
