### ISSUE TITLE
Automate Gobra's installation process

### ISSUE THREAD

**Issue by jcp19** [viperproject/gobra#298]
Currently, the set-up process for Gobra is rather annoying: the user has to download all dependencies and establish symbolic links to them. Furthermore, it is prone to problems because it does not enforce that the users install the correct versions of the dependencies. An automated set-up process should solve both of these issues.

**Comment by Felalolf** [comment]
Currently, all Scala projects using Viper (including Silver, Carbon, etc) have this problem. If we come up with a solution, before we implement it, we should discuss it with the rest of the Viper team. We want to avoid that we change the installation process too often.

**Comment by ArquintL** [comment]
Since parts of the project have already moved to submodules, the next step would simply be to use submodules in ViperServer too. Afterwards, getting the dependencies of Gobra boils down to simply recursively checkout submodules

**Comment by jcp19** [comment]
I think this can be closed now that we fully migrated to submodules
