### ISSUE TITLE
Generated Viper AST Should Be Consistent

### ISSUE THREAD

**Issue by ArquintL** [viperproject/gobra#302]
Currently, consistency checks do not pass for all generated Viper ASTs.
The encoding should be improved and the following line in `GobraTests` should be uncommented such that consistency is checked for all our regression tests (it is already enabled for `GobraPackageTests`):
```
backendConfig = ViperVerifierConfig.EmptyConfig(performConsistencyChecks = true)
```

**Comment by jcp19** [comment]
Looking at the slice encoding might be a good first step. A simple program like the following does not pass the consistency tests.
```go
package p

pure func f(a, b []byte) bool {
	return true
}
```

This is the corresponding error message:
```
[info] An assumption was violated during execution.
[info] Logic error: List(Consistency error: expected the same type, but got Slice[T] and Slice[T] (<no position>))
[info] viper.gobra.util.Violation$LogicException: Logic error: List(Consistency error: expected the same type, but got Slice[T] and Slice[T] (<no position>))
```

Also, the stubs for the std-lib also do not pass these consistency checks (PR #425)
