### ISSUE TITLE
Inconsistent punctuation of error messages

### ISSUE THREAD

**Issue by mlegner** [viperproject/gobra#326]
Some of the error messages in [VerifierError.scala](https://github.com/viperproject/gobra/blob/master/src/main/scala/viper/gobra/reporting/VerifierError.scala) end with `.`, others do not. I'm happy to open a PR if you tell me your preference.

**Comment by jcp19** [comment]
Hi @mlegner, thanks for reporting this. I addressed this issue in PR #327. Please let us know if you find any other issues :)
