### ISSUE TITLE
Support Method Declarations for non-struct Types

### ISSUE THREAD

**Issue by viper-admin** [viperproject/gobra#34]
> Created by **@arquintl** on 2020-06-17 13:59

Go supports methods for non-struct types but Gobra currently enforces that receiver are of struct type:

```
type MyType int

func (i MyType) Increment() (res MyType) {
    return i + 1
}

func foo() {
  i := MyType(1)
  j := i.Increment()
  assert i == j && j == 2
}
```

‌

**Comment by jcp19** [comment]
Fixed in #127 (not closed automatically for some reason)
