### ISSUE TITLE
Consistent Support of Old Expressions

### ISSUE THREAD

**Issue by viper-admin** [viperproject/gobra#39]
> Created by **@Felalolf** on 2020-07-07 16:10
> Last updated on 2020-07-09 12:49

Currently, the support of old has some flaws. Given labeled old expressions, the following Snippet verifies correctly:

```
package main

func test() {

  x1  := 5
  x2! := 5

  ghost L: // I added the label in the Viper file manually.

  x1 = 8
  x2 = 8

  assert old[L](x1) == 8 && old[L](x2) == 5
}
```

We should unify the behaviour of old on variables. I propose that we treat variables as entities that are affected by old, i.e. the labeled old expressions should evaluate to 5.

We can introduce further the concept of logical variables \(e.g. reusing ghost variables\) that have the same behaviour as variables in Viper.

Furthermore, we have to add support for labeled statements and labeled old expressions as shown above.

**Comment by Felalolf** [comment]
Fixed the issue in PR #239
