### ISSUE TITLE
Termination of pure functions with map look-ups

### ISSUE THREAD

**Issue by LinoTelschow** [viperproject/gobra#401]
Gobra cannot deduce that a pure function terminates when it performs a map look-up.
Example:
![image](https://user-images.githubusercontent.com/36457952/151382473-943157a9-f1b6-4d6a-a391-70554523400c.png)

![image](https://user-images.githubusercontent.com/36457952/151382525-dd277bc9-5b5c-4040-bd17-9fed8c4366ef.png)

UPDATE:
To debug the problem João's minimal example is much easier to work with.

Dependencies:
silver version: master branch: 7228e7144d41c91f02a70a68a93b6b3efae57d14
silicon version: master branch: 22551b40509c381991a493da0108ea4c97fd602d
carbon version: master branch: 4393d154a5ae24d994a0c2c578374bdd49c3a3b3
gobra versions: master branch: 47c3c47235d968372f76aef211a3f360f356d6b4

How to reproduce it:
1. Checkout the commit 21a2c5fa33d34a50770e5a6d6a0c758160ce861a of the `tlino-msg-verify-dataplane-part-2` branch of the verifiedSCION project.
2. Remove the _ after the `decreases` keyword in method  `GetLinkType` (line 215) in file gobra/pkg/router/dataplane.gobra
3. Run the following command in the sbt terminal:
`run -I PathToVerifiedSCION/VerifiedSCION/gobra/pkg/router/dataplane.gobra@216 PathToVerifiedSCION/VerifiedSCION/gobra/pkg/router/svc.gobra PathToVerifiedSCION/VerifiedSCION/gobra/pkg/router/metrics.gobra -I ../../VerifiedSCION`

where `PathToVerifiedSCION` is the path to the verifiedSCION project

**Comment by jcp19** [comment]
Minimal example:
```go
package pkg

type S struct {
    m map[int]int
}

pred Inv(s S) {
    acc(s.m)
}

requires acc(Inv(s), _)
decreases
pure func f(s S) int {
    return unfolding acc(Inv(s), _) in (s.m)[0]
}
```
Gobra cannot prove termination of `f`
