### ISSUE TITLE
Termination issues of pure functions that compare slices with nil

### ISSUE THREAD

**Issue by LinoTelschow** [viperproject/gobra#402]
Gobra cannot prove termination of this type of pure functions:
```
package testCases

type S struct {
    b []int
}

decreases
pure func check(s S) bool {
    return s.b == nil
}
```

![image](https://user-images.githubusercontent.com/36457952/151405420-778cba86-202f-4958-8037-b827739b5f99.png)

However, when the `pure` keyword is removed then the method verifies
i.e. this verifies without any error:
```
decreases
func check(s S) bool {
    return s.b == nil
}
```

Dependencies:
silver version: master branch: 7228e7144d41c91f02a70a68a93b6b3efae57d14
silicon version: master branch: 22551b40509c381991a493da0108ea4c97fd602d
carbon version: master branch: 4393d154a5ae24d994a0c2c578374bdd49c3a3b3
gobra version: master branch: 47c3c47235d968372f76aef211a3f360f356d6b4

**Comment by jcp19** [comment]
Likely related to #401
