### ISSUE TITLE
Interface methods calls do not check that the receiver is the `nil` of the interface type

### ISSUE THREAD

**Issue by jcp19** [viperproject/gobra#408]
The following code is accepted by Gobra, but compiling it and running it leads to a runtime execution because the var `x` in `main` is `nil` and its dynamic type does not allow to dispatch this call to one of the implementation methods.
```go
type T interface{
    f() int
}

type TImpl struct{}

func (x* TImpl) f() int {
    return 0
}

func main() {
    var x T
    x.f()
}
```

**Comment by jcp19** [comment]
A possible solution to this problem might be to generate a precondition for every interface method requiring that the receiver is not the `nil` value of  the interface type.

**Comment by Felalolf** [comment]
yeah, that is the solution. I will implement it.
