### ISSUE TITLE
Improve infile configs

### ISSUE THREAD

**Issue by viper-admin** [viperproject/gobra#41]
> Created by **@arquintl** on 2020-07-14 12:07

Currently, the same set of command line options are allowed as infile options. However, not all of them might make sense and/or a merge strategy would be intuitive. I see the following two options:

1. we create a second Scallop thingy that only deals with infile configs \(i.e. supports some subset of Gobra’s CLI options\)
2. we use the same Scallop class \(as it is now and which made the hack of adding the “-i” option necessary\) and adapt the `merge` function to ignore certain options

‌

**Comment by Felalolf** [comment]
@ArquintL  is still relevant. To me it seems that this was resolved.

**Comment by ArquintL** [comment]
It's still unclear how to merge certain options but in general I would say the current solution works.
