### ISSUE TITLE
Support for embedded fields

### ISSUE THREAD

**Issue by viper-admin** [viperproject/gobra#42]
> Created by **@arquintl** on 2020-07-14 15:33

The following code results in a cyclic welldefinedness check for the identifier `EmbeddedCell`:

```go
package main

type BarCell struct {
    val int
    EmbeddedCell
}

type EmbeddedCell struct {
    val2 int
}

func client() {
    c := BarCell{5, EmbeddedCell{6}};
    assert c.val == 5;
    assert c.val2 == 6;
    d := &BarCell{10, EmbeddedCell{11}};
    assert d.val == 10;
    assert d.val2 == 11;
}
```

‌

In addition, there is a related TODO in `embeddedDeclD` in the desugarer

**Comment by jcp19** [comment]
After fixing, file `src/test/resources/regressions/issues/000043.gobra` should be edited to uncomment test that relies on embedded fields.
