### ISSUE TITLE
Postconditions not allowed in specification of pure methods in interface definitions

### ISSUE THREAD

**Issue by jcp19** [viperproject/gobra#446]

**Comment by Felalolf** [comment]
Can you give a few examples that motivate this feature?

**Comment by jcp19** [comment]
Sure. This is an example from the `Hash` package in the std library. In particular, I want to specify `Size()` to be a pure function and to always return a positive number:

```go
type Hash interface {
	pred Mem()
	
        // io.Writer // not supported

        ...
	Sum(b []byte) (res []byte)

	// Size returns the number of bytes Sum will return.
	requires acc(Mem(), _)
	// ensures   res >= 0 // not allowed
	pure Size() (res int)
}
```

**Comment by ArquintL** [comment]
I've also just encountered this problem and would be keen on a fix / extension of the current approach
