### ISSUE TITLE
[syntactic sugar] Introduce `ignore` annotation

### ISSUE THREAD

**Issue by jcp19** [viperproject/gobra#543]
Often, it is useful to mark a method as ignored in a codebase that is partially verified, specially if the method is not called from the verified subset of the codebase. To that end, I suggest introducing an `ignored` annotation such that go does not complain about the method
```go
ignored
func f() {
    ...
}
```
which would be desugared to
```go
trusted // avoids desugaring the body
requires false // disallows calling the method
func f() {
    ...
}
```

**Comment by jcp19** [comment]
Building on top of this, we could even have a flag `--ignoreByDefault` which would treat every method without specification as `ignored`. This would, imo, be super useful for verifying already existing codebases (as opposed to verifying while programming), as the user would not need to comment/transform the codebase in order for gobra to not complain

**Comment by Felalolf** [comment]
why not remove the ignored methods entirely?

**Comment by jcp19** [comment]
I'm thinking of a gradual approach to verification, where you could start with all methods annotated with `// @ ignore`. In such a scenario, you could start verifying stuff from the leaves in the call-graph upwards. The advantage of this approach is that you can have a pre-existing codebase that compiles without having to change the original program at all
