### ISSUE TITLE
gobrafier: annotations are not Go 1.19 formatting compatible

### ISSUE THREAD

**Issue by oncilla** [viperproject/gobra#544]
Go has improve their support for doc comments with Go 1.19. As a result, the gofmt tool was adapted to support new rewrite rules and also adds spaces where it deems it appropriate.

Unfortunately, gofmt now adds spaces in front of the @ sign in the gobra annotations of Go code for doc comments.
This breaks the annotations as defined here;

https://github.com/viperproject/gobra/blob/01c38e0310eeee13ed0a4e5e86023119cb202312/src/main/scala/viper/gobra/frontend/Gobrafier.scala#L17-L18

We encountered this problem in when trying to upgrade our Go version to 1.19 in scionproto/scion#4271
When formatting the code, with gofmt 1.19, we encounter the following Gobra check error:

https://github.com/scionproto/scion/actions/runs/3197147933/jobs/5219993099

![image](https://user-images.githubusercontent.com/5121633/194513346-1ca85409-88fc-42d7-b3cb-f628c6e05783.png)

Dropping the space results in a passing check. But of course that is not really an option because then the file is not formatted according to gofmt -> it will be overwritten immediately in any editor that does auto formatting.

**Comment by jcp19** [comment]
Thank you @oncilla for reporting this! We will quickly discuss this in the Gobra team and adapt Gobra to support this new behavior. I guess that the easiest fix is to allow a space between `//` and `@`.

**Comment by jcp19** [comment]
@oncilla PR #545 should address this problem. As soon as our CI is done building a new docker image, I will create a new release of Gobra and Gobra-action and then I will open a PR in scion to use this new version. All of this will hopefully be done until the end of today
