### ISSUE TITLE
Improving scalability of parser and name resolution

### ISSUE THREAD

**Issue by viper-admin** [viperproject/gobra#6]
> Created by **@Felalolf** on 2019-07-23 22:11
> Last updated on 2019-07-24 09:53

I got a stackoverflow on example/sum.go and on the attached file.

---

Attachments:
* [**`manyAssignments.go`**](https://gist.githubusercontent.com/viper-admin/bf18adae059690c9690e7d5edf936c3a/raw/2580561c4a2789e8f3fdb29e961fcfb3d22534e4/manyAssignments.go)

**Comment by jcp19** [comment]
@Felalolf can we close this now?
