### ISSUE TITLE
Problem with Imports

### ISSUE THREAD

**Issue by Timon555** [viperproject/gobra#645]
Importing a package from a folder to another folder in the same hierarchy is currently not possible.

**Comment by ArquintL** [comment]
Thanks for reporting this issue. I'm not sure what you exactly mean by "in the same hierarchy". Could you sketch a problematic folder structure or even provide a minimal example?
Thanks!

**Comment by Timon555** [comment]
Let's say we have a folder named Gobra that contains two subfolders. It's not possible to import something from a file in one subfolder to a file in the other subfolder.

**Comment by ArquintL** [comment]
Thanks for the clarification. Does this correspond to the setup in the "distributed_interface_case" test case (i.e. `src/test/resources/regressions/features/interfaces/distributed_interface_case`)?
There, the `cellImplProof` package imports, e.g., package `cell`.
While we use in-file configuration options to make the unit test work, you can achieve the same by passing `-I <path to folder>` to Gobra. In your case described above, you would use the path to the folder named `Gobra`.

**Comment by jcp19** [comment]
@Timon555 can you please provide enough information for us to be able to debug it in the future? In particular, please either provide the code here or a link to it and describe the error messages that you get
