### ISSUE TITLE
Parse error if name of struct name has prefix of existing type

### ISSUE THREAD

**Issue by stammon** [viperproject/gobra#97]
If you have a struct whose name starts with a name of an existing type (such as int), the parser fails.

example:
``` go
package pkg;

type intPair struct {
    a int;
    b int;
};

func test(t intPair) (res int) {
    return t.a + t.b
}
```

When renaming intPair to twoInts, the parse error vanishes

**Comment by jcp19** [comment]
This bug was fixed by PR #99 and is already merged in master.
